import {
  Activity,
  Shield,
  Globe,
  Smartphone,
  Building2,
  BarChart3,
  TestTubeDiagonal,
  HeartPulse,
  Code2,
  Flame,
  Cpu,
} from 'lucide-react';

export const projectFilters = ['all', 'full-stack', 'frontend', 'mobile', 'personal'];

export const projects = [
  {
    icon: Activity,
    name: 'LZTB — TB-App',
    type: 'full-stack',
    typeLabel: 'full-stack',
    categories: ['full-stack'],
    desc: 'DOT-compliant clinical TB case management for Lunge Zürich — diagnostics, therapy, contact tracing, and screening in one workflow, with auto-saving forms and live lab-result screening tables.',
    tags: ['React 19', 'Vite', 'TanStack', 'Kotlin', 'Spring Boot', 'PostgreSQL', 'Azure AD'],
    scope: 'work',
    nda: true,
    flagship: true,
    home: true,
  },
  {
    icon: Globe,
    name: 'FiLiP CZ — Select Network',
    type: 'frontend',
    typeLabel: 'frontend',
    categories: ['frontend'],
    desc: 'Financial advisory portal for Swiss Life Select Czech Republic. Unifies customer, advisor, and admin portals with calculators, real-estate tools, e-signature, and 100+ shared packages.',
    tags: ['Angular', 'NgRx', 'SSR', 'PWA', 'ECAP3', 'SignalR'],
    scope: 'work',
    nda: true,
    home: true,
  },
  {
    icon: Shield,
    name: 'FiLiP SK — Select Network',
    type: 'frontend',
    typeLabel: 'frontend',
    categories: ['frontend'],
    desc: 'Insurance & wealth-management web portal for Swiss Life Select Slovakia. Multi-role portal serving customers, advisors, and admins with contract management, e-signatures, and campaign tools.',
    tags: ['Angular 13', 'NgRx', 'GraphQL', 'Apollo', 'SSR', 'PWA', 'SignalR'],
    scope: 'work',
    nda: true,
  },
  {
    icon: Smartphone,
    name: 'FiLiP Mobile — FC-CZ',
    type: 'mobile',
    typeLabel: 'mobile',
    categories: ['mobile'],
    desc: 'Cross-platform mobile app for Swiss Life Select CZ. Customer self-service portal with contract management, digital signatures, advisor chat, real-estate monitoring, and offline-first storage.',
    tags: ['NativeScript', 'Angular 11', 'CouchBase', 'Firebase', 'GraphQL', 'Biometrics'],
    scope: 'work',
    nda: true,
    home: true,
  },
  {
    icon: Building2,
    name: 'Adinova — Healthcare Advisory',
    type: 'full-stack',
    typeLabel: 'full-stack',
    categories: ['full-stack'],
    desc: 'Advisory management platform with built-in CRM and appointment scheduling — calendar sync, document management, and background jobs keep client workflows moving without manual chasing.',
    tags: ['Angular 21', '.NET 8', 'MongoDB', 'SignalR', 'Hangfire', 'RabbitMQ'],
    scope: 'work',
    nda: true,
    home: true,
  },
  {
    icon: BarChart3,
    name: 'OVB Stock App',
    type: 'frontend',
    typeLabel: 'frontend',
    categories: ['frontend'],
    desc: 'Financial/investment platform covering contracts, document management, appointments, real-time chat, e-signatures, review workflows, and goal tracking.',
    tags: ['Angular 20', 'Nx', 'NgRx', 'Tailwind', 'Chart.js', 'SignalR'],
    scope: 'work',
    nda: true,
    home: true,
  },
  {
    icon: TestTubeDiagonal,
    name: 'Automation Tool — INB',
    type: 'full-stack',
    typeLabel: 'full-stack',
    categories: ['full-stack'],
    desc: 'Enterprise multi-tenant test automation platform. Manages UI, API, and mobile test workflows with per-tenant isolation, scheduling, and real-time reporting.',
    tags: ['Angular 19', '.NET 8', 'MongoDB', 'SignalR', 'Docker', 'Tailwind'],
    scope: 'work',
    nda: true,
  },
  {
    icon: HeartPulse,
    name: 'FitMonitor',
    type: 'full-stack',
    typeLabel: 'full-stack',
    categories: ['full-stack', 'personal'],
    desc: 'A full-stack fitness tracker I’m building solo, end to end — React frontend, Spring Boot/Kotlin backend, JWT auth, PostgreSQL via Neon, deployed across Vercel and Render. No handoffs: architecture, database design, and deployment are all my calls.',
    tags: ['React 19', 'Spring Boot', 'Kotlin', 'PostgreSQL', 'Tailwind CSS v4'],
    scope: 'personal',
    status: 'building — workouts CRUD + exercise library in progress',
  },
  {
    icon: Code2,
    name: 'khalid.github.io',
    type: 'frontend',
    typeLabel: 'frontend',
    categories: ['frontend', 'personal'],
    desc: 'This portfolio itself — a single-page React build with custom routing, three theme-aware pages, and a dotted-grid aesthetic. You’re looking at it.',
    tags: ['React 19', 'Vite', 'Framer Motion'],
    scope: 'personal',
    links: [
      { label: 'live', href: 'https://khalidhasan01.github.io/' },
      { label: 'source', href: 'https://github.com/Khalidhasan01' },
    ],
  },
  {
    icon: Flame,
    name: 'CodePulse',
    type: 'full-stack',
    typeLabel: 'full-stack',
    categories: ['full-stack', 'personal'],
    desc: 'Learning project working the full ASP.NET Core lifecycle end to end — from HTTP pipeline to EF Core migrations and SQL Server persistence.',
    tags: ['.NET Core', 'Entity Framework', 'SQL Server'],
    scope: 'personal',
    status: 'exploration',
  },
  {
    icon: Cpu,
    name: 'Local AI setup',
    type: 'personal',
    typeLabel: 'personal',
    categories: ['personal'],
    desc: 'Running local models on Apple Silicon and exploring how they integrate into frontend projects — separating what is genuinely useful from what is merely new.',
    tags: ['Ollama', 'Qwen'],
    scope: 'personal',
    status: 'exploration — ongoing',
  },
];